### ISSUE TITLE
Seeduino Wio Lite W600 support

### ISSUE THREAD

**Issue by Tiagogv** [khoih-prog/ESP8266_AT_WebServer#3]
Does this library support also Wio Lite w600 from Seeduino?

**Comment by khoih-prog** [comment]
Thanks for your interest in the library.

Basically, this library supports boards, including SAMD21 as used in WIO Lite W600, using ESP8266-based AT-command, such as those mentioned in [**Currently-supported-at-command-shields**](https://github.com/khoih-prog/ESP8266_AT_WebServer#currently-supported-at-command-shields)

1. ESP8266-AT-command shield
2. ESP32-AT-command shield
3. W600 and WIS600-01S AT-command shield

As I don't have that WIO Lite W600 to test, I think, but not totally sure, that this library will support WIO Lite W600. You possibly have to modify the pin used to communicate between SAMD21 and W600 in the sketch.

If not, I don't have plan to order more boards to test, and add any more support, because there are too many products out there in the market.

Good Luck,
